# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: pwd
      #run: ./gradlew bootwar
    - uses: actions/checkout@master
    - name: Copy war to tomcat
      uses: canastro/copy-file-action@master
      with:
        source: "tests/a.txt"
        target: "test-a.txt"
      #run: cp build/libs/account-utils* ~
